"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GUI = exports.Controls = exports.Console = exports.Canvas = exports.Board = void 0;
var board_js_1 = require("./board.js");
Object.defineProperty(exports, "Board", { enumerable: true, get: function () { return board_js_1.Board; } });
var canvas_js_1 = require("./canvas.js");
Object.defineProperty(exports, "Canvas", { enumerable: true, get: function () { return canvas_js_1.Canvas; } });
var console_js_1 = require("./console.js");
Object.defineProperty(exports, "Console", { enumerable: true, get: function () { return console_js_1.Console; } });
var controls_js_1 = require("./controls.js");
Object.defineProperty(exports, "Controls", { enumerable: true, get: function () { return controls_js_1.Controls; } });
var gui_js_1 = require("./gui.js");
Object.defineProperty(exports, "GUI", { enumerable: true, get: function () { return gui_js_1.GUI; } });
