"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Timer = exports.ClockType = exports.ClockTick = exports.Position = exports.Speed = exports.Direction = exports.ScreenEdge = exports.GameKey = void 0;
var enums_js_1 = require("./enums.js");
Object.defineProperty(exports, "GameKey", { enumerable: true, get: function () { return enums_js_1.GameKey; } });
Object.defineProperty(exports, "ScreenEdge", { enumerable: true, get: function () { return enums_js_1.ScreenEdge; } });
Object.defineProperty(exports, "Direction", { enumerable: true, get: function () { return enums_js_1.Direction; } });
Object.defineProperty(exports, "Speed", { enumerable: true, get: function () { return enums_js_1.Speed; } });
var timer_js_1 = require("./timer.js");
Object.defineProperty(exports, "ClockTick", { enumerable: true, get: function () { return timer_js_1.ClockTick; } });
Object.defineProperty(exports, "ClockType", { enumerable: true, get: function () { return timer_js_1.ClockType; } });
Object.defineProperty(exports, "Timer", { enumerable: true, get: function () { return timer_js_1.Timer; } });
var position_js_1 = require("./position.js");
Object.defineProperty(exports, "Position", { enumerable: true, get: function () { return position_js_1.Position; } });
